name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
env:
  BEFORE_SHA: ${{ github.event.before }}
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin main

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run affected:test  -- --base=$BEFORE_SHA

      - name: Build
        run: npm run affected:build -- --base=$BEFORE_SHA

      - name: E2E tests
        run: npm run affected:e2e -- --base=$BEFORE_SHA

  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - run: git fetch origin main

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run affected:test --base=$BEFORE_SHA 

      - name: Build
        run: npm run affected:build --base=$BEFORE_SHA

      - name: E2E tests
        run: npm run affected:e2e --base=$BEFORE_SHA
