name: CI Maven
on:
  workflow_dispatch:
    paths-ignore:
      - '**.md'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run test nx-boot-maven

      - name: Build
        run: npm run build nx-boot-maven

      - name: E2E tests
        run: npm run e2e nx-boot-maven-e2e

  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run test nx-boot-maven

      - name: Build
        run: npm run build nx-boot-maven

      - name: E2E tests
        run: npm run e2e nx-boot-maven-e2e