name: nx-boot-gradle CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Unit tests 
        run: npm run test nx-boot-gradle 

      - name: Build 
        run: npm run build nx-boot-gradle 

      - name: E2E tests
        run: npm run e2e nx-boot-gradle-e2e 
