name: CI
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run affected:test 

      - name: Build
        run: npm run affected:build

      - name: E2E tests
        run: npm run affected:e2e

  windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run affected:test 

      - name: Build
        run: npm run affected:build

      - name: E2E tests
        run: npm run affected:e2e
