name: Check for new NX version

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - run: npm ci --force
    - uses: timonmasberg/nx-migration-gh-action@v1.1.2
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        # Optional:
        prTitle: 'Migrates NX to $VERSION'
        includeMigrationsFile: false # `migrations.json` will not be included in this PR.
        base: 'main'
